name: R Quant Systems
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74669
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#c2c2c2'
    - '#9d9d9d'
    - '#333333'
    - '#e4e4e4'
  brandStrength: 1
  lightness: 0.7173211898189038
  saturation: 0.6567027755081654
  rhythmicContrast: 0.3027292024344206
purpose: []
